### ISSUE TITLE
COSI driver should support multiple instances per K8s cluster if desired

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-cosi#27]
COSI's usage should allow for multiple Ceph COSI drivers per K8s cluster if users desire. Currently, it seems as though this is not allowed, based on example manifests:

This is the example COSI BucketClass:

```yaml
kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: sample-bcc
driverName: ceph.objectstorage.k8s.io # <-- this is not specific about which ceph COSI driver to select
deletionPolicy: Delete
parameters:
  objectStoreUserSecretName: rook-ceph-object-user-my-store-cosi
  objectStoreUserSecretNamespace: rook-ceph
```

Compare this to the CephFS CSI driver's example StorageClass from Rook:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-cephfs
provisioner: rook-ceph.cephfs.csi.ceph.com # <-- this specifies namespace, then "type" (cephfs)
parameters:
  # ... etc.
```

By specifying the namespace, CSI allows Rook to deploy its own but still allow users to have another custom-deployed version if desired. While we don't anticipate the need for this, it is probably best not to artificially limit what users are allowed to do.
